### ISSUE TITLE
pre-trained weights

### ISSUE THREAD

**Issue by hzd493** [mulns/AccFlow#1]
Hello author, could you please send me a pre-trained weights? Thanks.

**Comment by pokameng** [comment]
@mulns 
Hello author, could you please send me a pre-trained weights? Thanks.
and  can we chat with wechat？

**Comment by hzd493** [comment]
15862870455，my wechat，thanks.




Mes&nbsp;amis.
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "mulns/AccFlow"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年9月16日(星期六) 下午4:41
***@***.***&gt;;
抄送:&nbsp;"Mes ***@***.******@***.***&gt;;
主题:&nbsp;Re: [mulns/AccFlow] pre-trained weights (Issue #1)





 
@mulns
 Hello author, could you please send me a pre-trained weights? Thanks.
 and  can we chat with wechat？

**Comment by mulns** [comment]
The pre-trained weights are released now! Sorry for the delay...

**Comment by mulns** [comment]
> @mulns
> Hello author, could you please send me a pre-trained weights? Thanks.
> and can we chat with wechat？

Now release the pre-trained weight! Sorry for the delay...
My WeChat account is Mulns_X, please note your information when you add me
